---
version: "2.1"
services:
  pydio-sync-venv:
    container_name: pydio-sync-venv
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pydio-sync:/root/pydio-sync
      - ./opt:/opt
    entrypoint: /root/build-venv.sh

  pydio-sync-build:
    container_name: pydio-sync-build
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pydio-sync:/root/pydio-sync
      - ./opt:/opt
    working_dir: /root/pydio-sync
    entrypoint: python2 setup.py build
